CREATE TABLE IF NOT EXISTS pastas (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL UNIQUE,
    criado_em TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS arquivos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pasta_id INTEGER NOT NULL REFERENCES pastas(id) ON DELETE CASCADE,
    nome_original TEXT NOT NULL,
    nome_disco TEXT NOT NULL UNIQUE,
    tamanho INTEGER NOT NULL,
    criado_em TEXT NOT NULL
);
